In [60]:
import pandas as pd
import numpy as np

In [61]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [62]:
df=pd.read_csv("glass.csv")

In [63]:
df


RI     Na    Mg    Al     Si     K    Ca    Ba    Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.00     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.00     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.00     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.00     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.00     1
5    1.51596  12.79  3.61  1.62  72.97  0.64  8.07  0.00  0.26     1
6    1.51743  13.30  3.60  1.14  73.09  0.58  8.17  0.00  0.00     1
7    1.51756  13.15  3.61  1.05  73.24  0.57  8.24  0.00  0.00     1
8    1.51918  14.04  3.58  1.37  72.08  0.56  8.30  0.00  0.00     1
9    1.51755  13.00  3.60  1.36  72.99  0.57  8.40  0.00  0.11     1
10   1.51571  12.72  3.46  1.56  73.20  0.67  8.09  0.00  0.24     1
11   1.51763  12.80  3.66  1.27  73.01  0.60  8.56  0.00  0.00     1
12   1.51589  12.88  3.43  1.40  73.28  0.69  8.05  0.00  0.24     1
13   1.51748  12.86  3.56  1.27  73.21  0.54  8.38  0.00  0.17     1
14   1.51763  12.61  3.59  1.31  73.29  0.58  8.50  0.00  0.00     1
15   1.51761  12.81  3.54  1.23  73.24  0.58  8.39  0.00  0.00     1
16   1.51784  12.68  3.67  1.16  73.11  0.61  8.70  0.00  0.00     1
17   1.52196  14.36  3.85  0.89  71.36  0.15  9.15  0.00  0.00     1
18   1.51911  13.90  3.73  1.18  72.12  0.06  8.89  0.00  0.00     1
19   1.51735  13.02  3.54  1.69  72.73  0.54  8.44  0.00  0.07     1
20   1.51750  12.82  3.55  1.49  72.75  0.54  8.52  0.00  0.19     1
21   1.51966  14.77  3.75  0.29  72.02  0.03  9.00  0.00  0.00     1
22   1.51736  12.78  3.62  1.29  72.79  0.59  8.70  0.00  0.00     1
23   1.51751  12.81  3.57  1.35  73.02  0.62  8.59  0.00  0.00     1
24   1.51720  13.38  3.50  1.15  72.85  0.50  8.43  0.00  0.00     1
25   1.51764  12.98  3.54  1.21  73.00  0.65  8.53  0.00  0.00     1
26   1.51793  13.21  3.48  1.41  72.64  0.59  8.43  0.00  0.00     1
27   1.51721  12.87  3.48  1.33  73.04  0.56  8.43  0.00  0.00     1
28   1.51768  12.56  3.52  1.43  73.15  0.57  8.54  0.00  0.00     1
29   1.51784  13.08  3.49  1.28  72.86  0.60  8.49  0.00  0.00     1
..       ...    ...   ...   ...    ...   ...   ...   ...   ...   ...
184  1.51115  17.38  0.00  0.34  75.41  0.00  6.65  0.00  0.00     6
185  1.51131  13.69  3.20  1.81  72.81  1.76  5.43  1.19  0.00     7
186  1.51838  14.32  3.26  2.22  71.25  1.46  5.79  1.63  0.00     7
187  1.52315  13.44  3.34  1.23  72.38  0.60  8.83  0.00  0.00     7
188  1.52247  14.86  2.20  2.06  70.26  0.76  9.76  0.00  0.00     7
189  1.52365  15.79  1.83  1.31  70.43  0.31  8.61  1.68  0.00     7
190  1.51613  13.88  1.78  1.79  73.10  0.00  8.67  0.76  0.00     7
191  1.51602  14.85  0.00  2.38  73.28  0.00  8.76  0.64  0.09     7
192  1.51623  14.20  0.00  2.79  73.46  0.04  9.04  0.40  0.09     7
193  1.51719  14.75  0.00  2.00  73.02  0.00  8.53  1.59  0.08     7
194  1.51683  14.56  0.00  1.98  73.29  0.00  8.52  1.57  0.07     7
195  1.51545  14.14  0.00  2.68  73.39  0.08  9.07  0.61  0.05     7
196  1.51556  13.87  0.00  2.54  73.23  0.14  9.41  0.81  0.01     7
197  1.51727  14.70  0.00  2.34  73.28  0.00  8.95  0.66  0.00     7
198  1.51531  14.38  0.00  2.66  73.10  0.04  9.08  0.64  0.00     7
199  1.51609  15.01  0.00  2.51  73.05  0.05  8.83  0.53  0.00     7
200  1.51508  15.15  0.00  2.25  73.50  0.00  8.34  0.63  0.00     7
201  1.51653  11.95  0.00  1.19  75.18  2.70  8.93  0.00  0.00     7
202  1.51514  14.85  0.00  2.42  73.72  0.00  8.39  0.56  0.00     7
203  1.51658  14.80  0.00  1.99  73.11  0.00  8.28  1.71  0.00     7
204  1.51617  14.95  0.00  2.27  73.30  0.00  8.71  0.67  0.00     7
205  1.51732  14.95  0.00  1.80  72.99  0.00  8.61  1.55  0.00     7
206  1.51645  14.94  0.00  1.87  73.11  0.00  8.67  1.38  0.00     7
207  1.51831  14.39  0.00  1.82  72.86  1.41  6.47  2.88  0.00     7
208  1.51640  14.37  0.00  2.74  72.85  0.00  9.45  0.54  0.00     7
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.00     7
210  1.5

In [64]:
from sklearn.cross_validation import train_test_split

In [65]:

X=df.drop("Type",axis=1)
y=df["Type"]

In [66]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=101)

In [67]:
from sklearn.tree import DecisionTreeClassifier

In [68]:
dtree=DecisionTreeClassifier()

In [69]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [70]:
predictions=dtree.predict(X_test)
dtree.score(X_test,y_test)

0.6307692307692307

In [71]:
from sklearn.metrics import confusion_matrix,classification_report

In [72]:
confusion_matrix(y_test,predictions)

array([[19,  3,  4,  0,  0,  1],
       [ 3, 12,  0,  0,  1,  0],
       [ 1,  5,  3,  0,  0,  0],
       [ 0,  2,  0,  3,  0,  0],
       [ 1,  0,  1,  0,  2,  0],
       [ 0,  2,  0,  0,  0,  2]])

In [73]:
classification_report(y_test,predictions)

'             precision    recall  f1-score   support\n\n          1       0.79      0.70      0.75        27\n          2       0.50      0.75      0.60        16\n          3       0.38      0.33      0.35         9\n          5       1.00      0.60      0.75         5\n          6       0.67      0.50      0.57         4\n          7       0.67      0.50      0.57         4\n\navg / total       0.66      0.63      0.63        65\n'

In [74]:
from sklearn.ensemble import RandomForestClassifier


In [75]:
ran=RandomForestClassifier(n_estimators=200)

In [89]:
ran.fit(X_train,y_train)
from sklearn import tree
i_tree = 0
for tree_in_forest in ran.estimators_:
    with open('tree_' + str(i_tree) + '.dot', 'w') as my_file:
        my_file = tree.export_graphviz(tree_in_forest, out_file = my_file)
    i_tree = i_tree + 1
    break
# graph=graphviz.Source("random.dot")
# graph

In [77]:
rpredictions=ran.predict(X_test)

In [78]:
ran.score(X_test,y_test)

0.7076923076923077

In [79]:
confusion_matrix(y_test,rpredictions)

array([[24,  3,  0,  0,  0,  0],
       [ 1, 13,  0,  1,  1,  0],
       [ 5,  2,  2,  0,  0,  0],
       [ 0,  2,  0,  3,  0,  0],
       [ 1,  0,  0,  0,  2,  1],
       [ 1,  1,  0,  0,  0,  2]])

In [80]:
dtree.decision_path(X_train)

<149x61 sparse matrix of type '<class 'numpy.int64'>'
	with 981 stored elements in Compressed Sparse Row format>

In [81]:
import graphviz

In [82]:
nodes=dtree.tree_.node_count
nodes

61

In [83]:
child_left=dtree.tree_.children_left

child_left.size


61

In [84]:
child_right=dtree.tree_.children_right
child_right

array([56, 35, 32, 27, 10,  7, -1,  9, -1, -1, 22, 15, 14, -1, -1, 21, 18,
       -1, 20, -1, -1, -1, 24, -1, 26, -1, -1, 29, -1, 31, -1, -1, 34, -1,
       -1, 45, 38, -1, 44, 43, 42, -1, -1, -1, -1, 51, 48, -1, 50, -1, -1,
       53, -1, 55, -1, -1, 60, 59, -1, -1, -1])

In [85]:
feature=dtree.tree_.feature
feature

array([ 7,  3,  6,  2,  0,  4, -2,  0, -2, -2,  8,  5,  1, -2, -2,  0,  7,
       -2,  8, -2, -2, -2,  8, -2,  1, -2, -2,  6, -2,  2, -2, -2,  1, -2,
       -2,  2,  5, -2,  4,  4,  0, -2, -2, -2, -2,  0,  8, -2,  8, -2, -2,
        6, -2,  1, -2, -2,  4,  4, -2, -2, -2])

In [86]:
thres=dtree.tree_.threshold
thres

array([ 3.35000008e-01,  1.41999996e+00,  1.03199997e+01,  3.75500011e+00,
        1.51695001e+00,  7.27200012e+01, -2.00000000e+00,  1.51606488e+00,
       -2.00000000e+00, -2.00000000e+00,  1.94999993e-01,  1.25000000e-01,
        1.38199997e+01, -2.00000000e+00, -2.00000000e+00,  1.52174497e+00,
        4.50000018e-02, -2.00000000e+00,  8.50000009e-02, -2.00000000e+00,
       -2.00000000e+00, -2.00000000e+00,  2.70000011e-01, -2.00000000e+00,
        1.27900000e+01, -2.00000000e+00, -2.00000000e+00,  8.58500004e+00,
       -2.00000000e+00,  3.79500008e+00, -2.00000000e+00, -2.00000000e+00,
        1.41949997e+01, -2.00000000e+00, -2.00000000e+00,  2.55500007e+00,
        6.49999976e-02, -2.00000000e+00,  7.22050018e+01,  7.13300018e+01,
        1.51781499e+00, -2.00000000e+00, -2.00000000e+00, -2.00000000e+00,
       -2.00000000e+00,  1.51732492e+00,  2.29999989e-01, -2.00000000e+00,
        2.74999976e-01, -2.00000000e+00, -2.00000000e+00,  8.54500008e+00,
       -2.00000000e+00,  

In [87]:
from sklearn import tree

dot_data =tree.export_graphviz(dtree,out_file='random.dot')
# graph=graphviz.Source("random.dot")
# graph

NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.